port: 8888
runMode: dev
# logger configuration
log:
  prefix: '[APP-ROBOT-SERVER]'
  level: 'DEBUG'
  saveFile: false

#jwt configuration
jwt:
  signingKey: '!v@8#z$%v^t&g*('
  tokenExpiration: 2 #Token expiration time unit: hour

#mongodb configuration
mongo:
  connURI: mongodb://admin:123456@localhost:27017
  dbName: robot
  usersCollection: users
  pluginsCollection: plugins
  instanceCollection: instances

#kubernetes configuration
kubernetes:
  kubeConfigPath: "c:/config/fighting.yaml"
  namespace: robot-plugin

