basePath: /v1
definitions:
  models.BaseResponse:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  models.LoginResult:
    properties:
      token:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: plugin maintenance server api doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger app-robot-server API
  version: 0.0.1
paths:
  /accounts/code:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 邮件发送成功
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 账号注册获取验证码
      tags:
      - Accounts
  /accounts/email:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 邮箱可用
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "400":
          description: 邮箱已注册
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 返回失败状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 邮箱是否已注册
      tags:
      - Accounts
  /accounts/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 账号
        in: formData
        name: account
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回token和userId
          schema:
            allOf:
            - $ref: '#/definitions/models.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.LoginResult'
              type: object
        "400":
          description: 错误返回
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "403":
          description: 错误返回
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 错误返回
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 账号密码登录
      tags:
      - Accounts
  /accounts/password:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 邮件发送成功
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "400":
          description: 邮箱校验失败
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 返回失败状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 发送找回密码邮件
      tags:
      - Accounts
    patch:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: the key
        in: formData
        name: key
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: new password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 邮件发送成功
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "400":
          description: 重置失败
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "403":
          description: 验证失败
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 返回失败状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 邮件验证重置密码
      tags:
      - Accounts
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户ID
        in: formData
        name: userID
        required: true
        type: string
      - description: 旧密码
        in: formData
        name: password
        required: true
        type: string
      - description: 新密码
        in: formData
        name: newPassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 修改成功
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "400":
          description: 修改失败
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "401":
          description: token验证失败
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/models.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: 重置密码
      tags:
      - Accounts
  /accounts/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      - description: 用户名(仅字母数字组合)
        in: formData
        name: username
        required: true
        type: string
      - description: 密码（大小字母数字特殊字符满足三种）
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 返回成功状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "400":
          description: 返回失败状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 返回失败状态
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 账号注册
      tags:
      - Accounts
  /accounts/username:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户名可用
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: 用户名已注册
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: 用户名是否可用
      tags:
      - Accounts
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: access-token
    type: apiKey
swagger: "2.0"
